export default {
    SET_DRAG_COMPONENT: 'SET_DRAG_COMPONENT',
    GET_DRAG_COMPONENT: 'GET_DRAG_COMPONENT',
    SET_GRID_OK: 'SET_GRID_OK',

    CREATE_GRID: 'CREATE_GRID',
    CREATE_GRID_OK: 'CREATE_GRID_OK',
    UPDATE_GRID: 'UPDATE_GRID',
    UPDATE_GRID_OK: 'UPDATE_GRID_OK',
    FETCH_GRID: 'FETCH_GRID',
    FETCH_GRID_OK: 'FETCH_GRID_OK',
    REMOVE_GRID: 'REMOVE_GRID',
    REMOVE_GRID_OK: 'REMOVE_GRID_OK',
}